import tkinter as tk
from tkinter import messagebox
class SignUp:
    def __init__(self):
        self.Main_window = tk.Tk()
        self.Main_window.title("SignUp")
        self.Main_window.geometry("500x500")
        self.Main_window.configure(background="white")
        self.frame1 = tk.Frame(self.Main_window)
        self.frame2= tk.Frame(self.Main_window)
        self.frame3 = tk.Frame(self.Main_window)
        self.frame4 = tk.Frame(self.Main_window)
        self.frame5 = tk.Frame(self.Main_window)
        self.frame6 = tk.Frame(self.Main_window)
        self.frame7 = tk.Frame(self.Main_window)
        self.frame8 = tk.Frame(self.Main_window)
        self.label = tk.Label(self.frame1, text="Sign Up")
        self.label2 = tk.Label(self.frame2, text="First Name")
        self.label3 = tk.Label(self.frame3, text="Last Name")
        self.label4 = tk.Label(self.frame4, text="ID")
        self.label5 = tk.Label(self.frame5, text="Password")
        self.label6 = tk.Label(self.frame6, text="Email")
        self.label7 = tk.Label(self.frame7, text="Number")
        self.Fname_entry = tk.Entry(self.frame2)
        self.Lname_entry = tk.Entry(self.frame3)
        self.Id_entry = tk.Entry(self.frame4)
        self.Password_entry = tk.Entry(self.frame5)
        self.Email_entry = tk.Entry(self.frame6)
        self.number_entry = tk.Entry(self.frame7)
        self.button1=tk.Button(self.frame8,text="student login",command=)
        self.button2=tk.Button(self.frame8,text="Admin login",command=)

        self.label1.pack()
        self.label2.pack(side=tk.LEFT)
        self.Fname_entry.pack(side=tk.RIGHT)
        self.label3.pack(side=tk.LEFT)
        self.Lname_entry.pack(side=tk.RIGHT)
        self.label4.pack(side=tk.LEFT)
        self.Id_entry.pack(side=tk.RIGHT)
        self.label5.pack(side=tk.LEFT)
        self.Password_entry.pack(side=tk.RIGHT)
        self.label6.pack(side=tk.LEFT)
        self.Email_entry.pack(side=tk.RIGHT)
        self.label7.pack(side=tk.LEFT)
        self.number_entry.pack(side=tk.RIGHT)
        self.button1.pack(side=tk.LEFT)
        self.button2.pack(side=tk.RIGHT)

        tk.mainloop()

test=SignUp()
